services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_USER=root
      - POSTGRES_DB=dhcp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
