interfaces:
  - eth0
  - eth1
leaseTime: 3600
subnets:
  - cidr: 192.168.0.0/25
    router: 192.168.0.1
    dns: [192.168.0.2]
    leaseTime: 7200
    options:
      - code: 190
        value: ""
      - code: 191
        value: "ffffff"
    pools:
      - startAddress: 192.168.0.50
        endAddress: 192.168.0.60
        onlyReservedLease: true
        leaseTime: 10800
        reservation:
          - hwAddress: 00:00:00:00:00:01
            ipAddress: 192.168.0.50
          - hwAddress: 00:00:00:00:00:02
            ipAddress: 192.168.0.60
        options:
          - code: 200
            value: "0102030405"
          - code: 201
            value: "0a0bff10"
      - startAddress: 192.168.0.70
        endAddress: 192.168.0.90
        onlyReservedLease: false
        leaseTime: 50000
        reservation:
          - hwAddress: 00:00:00:11:11:11
            ipAddress: 192.168.0.70
          - hwAddress: 00:00:00:22:22:22
            ipAddress: 192.168.0.72
        options:
          - code: 210
            value: ""
          - code: 211
            value: "1111111111111111"
  - cidr: 172.16.0.0/16
    router: 172.16.100.0
    dns: [172.16.100.1, 172.16.100.2]
    leaseTime: 100000
    options:
      - code: 190
        value: ""
    pools:
      - startAddress: 172.16.10.0
        endAddress: 172.16.20.0
        onlyReservedLease: true
        leaseTime: 10800
        reservation:
          - hwAddress: 00:00:00:aa:aa:aa
            ipAddress: 172.16.10.0
          - hwAddress: 00:00:00:bb:bb:bb
            ipAddress: 172.16.10.1
        options:
          - code: 230
            value: "0102030405"
          - code: 231
            value: "0a0bff10"

database:
  type: postgresql
  postgresql-option:
    jdbc-url: jdbc:postgresql://localhost:5432/dhcp
    username: root
    password: p@ssw0rd
    database-name: dhcp
    server-name: localhost
    port-number: 5432

httpApi:
  enabled: false
  port: 8080

webhook:
  events:
    - lease
  url: http://localhost:8000
