interfaces:
  - eth0
  - eth1
foo: bar
leaseTime: -100
subnets:
  - cidr: baz
  - cidr: 192.168.0.0/24
    router: 192.168.0.1
    leaseTime: 999999
    pools:
      - startAddress: 192.168.0.50
        endAddress: 192.168.0.60
        onlyReservedLease: true
        leaseTime: 1000
        reservation:
          - hwAddress: 00:00:00:00:00:00
            ipAddress: 192.168.0.55
        options:
          - code: 200
            value: "0102030405"
    dns: [192.168.0.10, 192.168.0.20]
  - cidr: 192.168.0.1/24
    router: xxxx
    pools: ["test"]
    dns: ["xyz"]

database:
  type: unknown

