name: Lint and Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cljstyle: latest
          clj-kondo: latest
      - run: cljstyle check --report -v
      - run: clj-kondo --lint src --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17', '21']
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: rocksaw-1.1.0-src.tar.gz
          key: rocksaw-src-1.1.0
      - name: build rocksaw
        run : ./build-rocksaw.sh
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      - run: clojure -M:dev:test
